samples/OSky.UI.Admin/Areas/Admin/Controllers/Flow/ScheduleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using System.ComponentModel;
using OSky.Web.Mvc.Security;
using OSky.Web.Mvc.UI;
using OSky.UI.Contracts;
using OSky.Web.Mvc.Extensions;
using OSky.UI.Dtos.Flow;
using OSky.Utility.Extensions;
using OSky.UI.Models.Flow;
using OSky.Core.Data.Extensions;
using OSky.Utility.Data;
using System.Threading.Tasks;
using Microsoft.AspNet.SignalR;

namespace OSky.UI.Admin.Areas.Admin.Controllers
{
    [Description("工作流-待办事项")]
    public class ScheduleController : AdminBaseController
    {
        /// <summary>
        /// 获取或设置 工作流业务对象
        /// </summary>
        public IFlowContract FlowContract { get; set; }

        #region Ajax功能

        #region 获取数据

        [AjaxOnly]
        [Description("工作流-待办事项-列表数据")]
        public ActionResult GridData()
        {
            GridRequest request = new GridRequest(Request);
            var predicate = ExpressionExtensions.True<WorkFlowTask>();
            predicate = predicate.And(c => (c.Status == 1 || c.Status == 2) && c.ReceiverId == Operator.UserId);
            var page = FlowContract.FlowTasks.ToPage(predicate, request.PageCondition, m => new
                {
                    m.Id,
                    m.FlowItemId,
                    m.FlowItem.FlowDesignId,
                    m.FlowItem.EntityId,
                    m.FlowItem.EntityName,
                    m.StepName,
                    m.SenderName,
                    m.CreatedTime,
                    m.Status,
                    m.StepDay,
                    m.DelayDay,
                    m.DelayReason
                });
            return Json(page.ToGridData(), JsonRequestBehavior.AllowGet);

        }
        [HttpPost]
        [AjaxOnly]
        [Description("工作流-任务-记录数")]
        public ActionResult GetTaskCount()
        {
            int taskCount = FlowContract.FlowTasks.Count(c => c.Status <= 2 && c.ReceiverId == Operator.UserId);
            return Json(taskCount, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region 功能方法

        [HttpPost]
        [AjaxOnly]
        [Description("工作流-任务-查看")]
        public ActionResult Scan(Guid TaskId)
        {
            return Json(FlowContract.OpenTask(TaskId).ToAjaxResult(), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [AjaxOnly]
        [Description("工作流-任务-受理")]
        public ActionResult StartFlow(FlowExecuteDto dto)
        {
            dto.TaskId = Guid.Empty;
            dto.ExecuteType = ExecuteType.Submit;
            dto.SenderId = Operator.UserId;
            dto.SenderName = Operator.NickName;
            var re = FlowContract.Execute(dto);
            //推送
            ExecTask();

            return Json(re.ToAjaxResult(), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [AjaxOnly]
        [Description("工作流-任务-审核")]
        public ActionResult ExecuteAudit(FlowProjectDto dto)
        {
            var Edto = new FlowExecuteDto()
            {
                FlowId = dto.FlowId,
                TaskId = dto.TaskId,
                ItemId = dto.ItemId,
                ExecuteType = ExecuteType.Submit,
                SenderId = Operator.UserId,
                SenderName = Operator.NickName
            };
            //推送
            ExecTask();

            return Json(Execute(Edto), JsonRequestBehavior.AllowGet);

        }

        [Description("工作流-任务-发送")]
        public ActionResult Execute(FlowExecuteDto dto)
        {
            var steps = new Dictionary<int, Dictionary<string,string>>();
            if (!string.IsNullOrEmpty(Request.Params["stepCheck"]))
            {
                var stepsIds = Request.Params["stepCheck"].Split(',');
                foreach (var stepId in stepsIds)
                {
                    if (!string.IsNullOrEmpty(Request.Params["stepCheck_receive_Id_" + stepId]))
                    {
                        var userIds = Request.Params["stepCheck_receive_Id_" + stepId].Split(',');
                        var userNames = Request.Params["stepCheck_receive_Name_" + stepId].Split(',');
                        var userList = new Dictionary<string,string>();
                        for (int i = 0; i < userIds.Length;i++ )
                        {
                            userList.Add(userIds[i],userNames[i]);
                        }
                        steps.Add(int.Parse(stepId), userList);
                    }
                }
            }
            dto.ExecuteType = ExecuteType.Submit;
            dto.SenderId = Operator.UserId;
            dto.SenderName = Operator.NickName;
            dto.Steps = steps;
            if (steps == null)
                return Json(new OperationResult(OperationResultType.Error, "请指定发送人！").ToAjaxResult());
            //推送
            ExecTask();

            return Json(FlowContract.Execute(dto).ToAjaxResult(), JsonRequestBehavior.AllowGet);
        }

        [AjaxOnly]
        [HttpPost]
        [Description("工作流-任务-完成")]
        public ActionResult Completed(Guid TaskId)
        {
            FlowExecuteDto execut = new FlowExecuteDto()
            {
                TaskId = TaskId,
                ExecuteType = ExecuteType.Completed,
                SenderName = Operator.NickName
            };
            //推送
            ExecTask();

            return Json(FlowContract.Execute(execut).ToAjaxResult(), JsonRequestBehavior.AllowGet);
        }

        [Description("工作流-任务-退回")]
        public ActionResult Backed(FlowExecuteDto dto)
        {
            var steps = new Dictionary<int, Dictionary<string,string>>();
            if (!string.IsNullOrEmpty(Request.Params["stepCheck"]))
            {
                var stepsIds = Request.Params["stepCheck"].Split(',');
                foreach (var stepId in stepsIds)
                {
                    steps.Add(int.Parse(stepId), null);
                }
            }
            dto.ExecuteType = ExecuteType.Back;
            dto.SenderId = Operator.UserId;
            dto.SenderName = Operator.NickName;
            dto.Steps = steps;
            if (steps == null)
                return Json(new OperationResult(OperationResultType.Error, "请指定退回人！"));
            //推送
            ExecTask();

            return Json(FlowContract.Execute(dto).ToAjaxResult(), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [AjaxOnly]
        [Description("工作流-任务-撤销")]
        public ActionResult CallBack(Guid TaskId)
        {
            FlowExecuteDto dto = new FlowExecuteDto()
            {
                TaskId = TaskId,
                ExecuteType = ExecuteType.CallBack
            };
            //推送
            ExecTask();

            return Json(FlowContract.Execute(dto).ToAjaxResult(), JsonRequestBehavior.AllowGet);
        }

        #endregion

        #endregion

        #region 视图功能

        [Description("工作流-待办事项-列表")]
        public ActionResult Index()
        {
            return View();
        }

        [Description("工作流-待办事项-办理信息")]
        public ActionResult FlowHandle(FlowProjectDto dto)
        {
            var form = FlowContract.FlowRelateForms.Where(c => c.FlowDesignId == dto.FlowId).Select(m => new { m.FlowForm.FilePath, m.FlowForm.ActionPath }).SingleOrDefault();
            dto.FileUrl = form.FilePath;
            dto.ActionUrl = form.ActionPath;
            return View(FlowContract.GetFlowOperateStatus(dto, Operator.UserId));
        }

        [Description("工作流-任务-发送下一步")]
        public ActionResult ExecuteForm(FlowExecuteFormDto dto)
        {
            dto = FlowContract.GetFlowNextStep(dto);
            return View(dto);
        }

        [Description("工作流-任务-退回")]
        public ActionResult ExecuteBack(Guid TaskId, Guid FlowId)
        {
            return View(FlowContract.GetBackSteps(TaskId,FlowId));
        }

        [Description("工作流-任务-审批过程")]
        public ActionResult ApprovalList(Guid ItemId)
        {
            var list = FlowContract.FlowTasks.Where(c => c.FlowItemId == ItemId).Select(m => new FlowApprovalDto{ 
                StepName=m.StepName,
                SenderName=m.SenderName,
                CreatedTime=m.CreatedTime,
                ReceiverName=m.ReceiverName,
                CompletedTime=m.CompletedTime,
                Status=m.Status,
                Comment=m.Comment,
                TaskNote=m.TaskNote
            }).ToList();
            return View(list);
        }
        #endregion

        #region 内部方法

        private void ExecTask()
        {
            int taskCount = FlowContract.FlowTasks.Count(c => c.Status <= 2 && c.ReceiverId == Operator.UserId);
            //线程推送
            Task.Factory.StartNew(
                () =>
                {
                    IHubContext hubcontext = GlobalHost.ConnectionManager.GetHubContext<SignalFlowService>();
                    hubcontext.Clients.All.AddTask(taskCount);
                });
        }

        #endregion
    }
}

samples/OSky.UI.Admin/Areas/Admin/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using System.ComponentModel;
using System.Drawing.Imaging;
using System.IO;
using OSky.Utility.Drawing;
using OSky.Utility.Data;
using OSky.UI.Dtos.Identity;
using OSky.Utility;
using OSky.Utility.Secutiry;
using OSky.UI.Contracts;
using System.Security.Claims;
using Microsoft.AspNet.Identity;
using OSky.UI.Models.Identity;
using System.Net;
using Microsoft.Owin.Security;
using System.Text;
using OSky.Core.Exceptions;

namespace OSky.UI.Admin.Areas.Admin.Controllers
{
    [Description("管理-登录")]
    public class LoginController : Controller
    {
        /// <summary>
        /// 获取或设置 身份认证业务对象
        /// </summary>
        public IIdentityContract IdentityContract { get; set; }
        private IAuthenticationManager AuthenticationManager { get { return HttpContext.GetOwinContext().Authentication; } }

        #region Ajax功能

        #region 获取数据

        [Description("管理-登录-验证码")]
        public ActionResult ValidateCode()
        {
            string strCoder = "";
            ValidateCoder vCoder = new ValidateCoder() { Height = 32, RandomColor = true, RandomPosition = false, RandomItalic = false };
            MemoryStream ms = new MemoryStream();
            vCoder.CreateImage(4, out strCoder, ValidateCodeType.NumberAndLetter).Save(ms, ImageFormat.Jpeg);
            Session["ValidateCode"] = strCoder;
            return File(ms.GetBuffer(), @"image/jpeg");
        }
       
        #endregion

        #region 功能方法

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Description("管理-登录-验证")]
        public ActionResult Login(LoginDto dto)
        {
            dto.CheckNotNull("dto");
            OperationResult result = new OperationResult(OperationResultType.ValidError);
            if (ModelState.IsValid)
            {
                try
                {
                    if (Session["ValidateCode"] == null|| !dto.CheckCode.ToLower().Equals(Session["ValidateCode"].ToString().ToLower()))
                    {
                        ModelState.AddModelError("CheckCode", "验证码不正确!");
                    }
                    else
                    {
                        //CommunicationCryptor cryptor = new CommunicationCryptor("", "", "SHA1");
                        //dto.LoginPwd = cryptor.EncryptData(dto.LoginPwd);
                        result = IdentityContract.CheckLogin(dto);
                        if (result.ResultType == OperationResultType.Success)
                        {
                            User user = result.Data as User;
                           
                            AuthenticationManager.SignOut(DefaultAuthenticationTypes.ApplicationCookie);
                            AuthenticationManager.SignIn(new AuthenticationProperties() { IsPersistent = false },
                                new ClaimsIdentity(DefaultAuthenticationTypes.ApplicationCookie).SetClaimsIdentity(user.Id.ToString(), user.UserName,user.NickName, null ));
                            return RedirectToAction("Index", "Home", new { });
                            
                        }
                        else
                        {
                            ModelState.AddModelError("LoginName", result.Message);
                        }
                    }
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("Exception", ex.Message);
                }
            }
            ViewBag.ErrorsMessage = GetModelErrors(ModelState);
            return View(dto);
        }


        [Description("管理-登录-退出")]
        public ActionResult LoginOut()
        {
            AuthenticationManager.SignOut(DefaultAuthenticationTypes.ApplicationCookie);
            Response.Redirect("Index");  
            return View();
        }

        #endregion

        #endregion

        #region 视图功能
        //
        // GET: /Admin/Login/
        [Description("管理-登录-访问")]
        public ActionResult Index(LoginDto dto)
        {
            if(dto.LoginName==null)
                return View(dto);
            return Login(dto);
        }

        #endregion

        public string GetModelErrors(ModelStateDictionary modelState)
        {
            var errorList = modelState.Values.Where(c => c.Errors.Count > 0).ToList();
            StringBuilder sb = new StringBuilder();
            foreach (var item in errorList)
            {
                sb.Append("【" + item.Errors[0].ErrorMessage + "】");
            }
            return sb.ToString();
        }


	}
}

samples/OSky.UI.Admin/Controllers/HomeController.cs
// -----------------------------------------------------------------------
//  <copyright file="HomeController.cs" company="">
//      Copyright (c) 2014-2015 OSky. All rights reserved.
//  </copyright>
//  <last-editor>Lmf</last-editor>
//  <last-date>2015-07-14 1:02</last-date>
// -----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using OSky.Utility.Logging;
using OSky.Web.Mvc.Logging;


namespace OSky.UI.Admin.Controllers
{
    [OperateLogFilter]
    [Description("网站")]
    public class HomeController : Controller
    {
        private static readonly ILogger Logger = LogManager.GetLogger(typeof(HomeController));

        [Description("网站-首页")]
        public ActionResult Index()
        {
            Logger.Debug("访问首页，将转向到后台管理首页");
            //return RedirectToAction("Index", "Home", new { area = "Admin" });
            //var data = new
            //{
            //    OrganizationCount = _identityContract.Organizations.Count(),
            //    UserCount = _identityContract.Users.Count(),
            //    RoleCount = _identityContract.Roles.Count()
            //};
            //ViewBag.Data = data.ToDynamic();
            return View();
        }
    }
}

samples/OSky.UI.Admin/Areas/Admin/Views/Home/Index.cshtml
@{
    ViewBag.Title = "OSky后台管理";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    string navDataUrl = Url.Action("GetMenuData");
}
@section header{
    <style>
        li:hover {
            background-color: #eee;
        }
        a p {
            margin: 0 0 0 -8px;
            -webkit-box-sizing: border-box;
        }
        a p.counter {
            position: absolute;
            top: 8px;
            height: 18px;
            min-width: 18px;
            padding: 5px -2px 0px 1px;
            border-radius: 9px;
            background: #e62828;
            text-align: center;
            line-height: 17px;
            color: white;
            font-size: 11px;
        }
        ul,li{
            padding: 0 0px;
            margin: 0 0 0 0px !important;
        }
        .ulclass li {
            list-style-type: none;
            float: left;
            display: block;
            padding: 15px 20px 25px 20px;
        }
        .aspan {
            position: absolute;
            margin: 0 0 0 -12px;
            color: #aaa;
        }
    </style>

    }

<div class="easyui-layout" data-options="fit:true">
    <div data-options="region:'north', height:70" @*style="padding: 10px; background: #2D3E50; color: #fff; "*@>
        <span style="font-size: 18px;">OSky后台管理系统</span>
        <a href="/" target="_blank">返回首页</a>
        <div style="float:right;padding:2px 20px 0px 30px;">
            <ul class="ulclass" style="float:left;">
                <li>
                    <a href="#" onclick="click_atask()" style=" text-decoration: none;">
                        <span class="icon-bell" style="font-size: 24px;color:#aaa;"></span>
                        <p id="pTaskCount" class="counter" style="display:none;"></p>
                        <span class="aspan">代办任务</span>
                    </a>
                </li>
                <li>
                    <a href="#" style="text-decoration:none;">
                        <span class=" icon-cog" style="font-size: 24px;color:#aaa;"></span>
                        <span class="aspan">系统登录</span>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("LoginOut","Login")" style="text-decoration:none;">
                        <span class="icon-signout" style="font-size: 24px;color:#aaa;"></span>
                        <span class="aspan">退出登录</span>
                    </a>
                </li>
            </ul>
            
        </div>
    </div>
    <div data-options="region:'west', split:true, minWidth:100, width:230, title:'导航菜单'">
        <div id="main-nav" class="easyui-accordion" data-options="fit:true, border:false, selected:true">

        </div>
    </div>
    <div data-options="region:'center'">
        <div id="main-tab" class="easyui-tabs" data-options="fit:true, border:false">
            <div title="我的主页" iconcls="pic_209" style="padding: 5px;">
                <iframe width="100%" height="100%" frameborder="0" src="@Url.Action("Welcome")" marginheight="0" marginwidth="0"></iframe>
            </div>
        </div>
    </div>
    <div data-options="region:'south', height:40">
        <p style="text-align:center; line-height:20px;">Copyright &copy; OSky 2014 - @DateTime.Now.Year</p>
    </div>
</div>
<div id="tab-menu" class="easyui-menu" style="width: 150px;">
    <div id="tab-menu-refresh" data-options="iconCls:'icon-reload'">刷新</div>
    <div id="tab-menu-openFrame" data-options="iconCls:'pic_138'">新窗口打开</div>
    <div class="menu-sep"></div>
    <div id="tab-menu-close" data-options="iconCls:'icon-remove'">关闭</div>
    <div id="tab-menu-closeleft" data-options="iconCls:'icon-undo'">关闭左边</div>
    <div id="tab-menu-closeright" data-options="iconCls:'icon-redo'">关闭右边</div>
    <div class="menu-sep"></div>
    <div id="tab-menu-closeother" data-options="iconCls:'pic_101'">关闭其他</div>
    <div id="tab-menu-closeall" data-options="iconCls:'pic_283'">关闭所有</div>
</div>

@section footer{
    <script src="~/scripts/plugins/jquery.signalr-2.2.0.min.js"></script>
    <script src="@Url.Content("~/signalr/hubs")" type="text/javascript"></script>
    <script type="text/javascript">

        var chatHub = $.connection.SignalFlow;

        registerClientMethods(chatHub);
        registerEvents(chatHub);

        $.connection.hub.start();

        //注册客户端方法
        function registerClientMethods(chatHub) {

            chatHub.client.AddTask = function (taskCount) {
                Display_P(taskCount);
            }
        }

        //注册客户端事件
        function registerEvents(chatHub) {

            //$("#a_daib").click(function () {
            //    chatHub.server.sendScheduleTaskCount("1");
            //});
        }
        
        function Display_P(count)
        {
            var p = $("#pTaskCount");
            if (count > 0) {
                p.html(count);
                p.show();
            } else {
                p.hide();
            }

        }

        function click_atask() {
            addTab("代办事宜", "@Url.Action("Index", "Schedule")", "pic_123");
        }

        $(function () {
            $.getJSON("@navDataUrl", function(data) {
                if (data.length == 0) {
                    return;
                }
                //第一层生成手风琴的项
                $.each(data, function(i, item) {
                    var id = item.Id;
                    $("#main-nav").accordion("add", {
                        title: item.Text,
                        content: "<ul id='tree-" + id + "'></ul>",
                        selected: true,
                        iconCls: item.IconCls
                    });
                    $.parser.parse();
                    //第二层生成树节点
                    if (!item.Children || item.Children.length == 0) {
                        return true;
                    }
                    var treeData = transToTreeData(item.Children);
                    $("#tree-" + id).tree({
                        data: treeData,
                        onClick: function(node) {
                            if (node.attributes) {
                                var tabTitle = node.text;
                                var url = node.attributes.url;
                                var icon = node.iconCls;
                                addTab(tabTitle, url, icon);
                            }
                        }
                    });
                });
            });

            $("#main-tab").tabs({
                onContextMenu: function(e, title) {
                    e.preventDefault();
                    $("#tab-menu").menu("show", { left: e.pageX, top: e.pageY })
                        .data("tabTitle", title); //将点击的Tab标题加到菜单数据中
                }
            });

            $("#tab-menu").menu({
                onClick: function(item) {
                    tabHandle(this, item.id);
                }
            });

            //获取代办数
            $.post("@Url.Action("GetTaskCount","Schedule")", function (count) {
                var p = $("#pTaskCount");
                if (count > 0) {
                    p.html(count);
                    p.show();
                } else {
                    p.hide();
                }
            });

        });

        function addTab(title, url, icon) {
            var $mainTabs = $("#main-tab");
            if ($mainTabs.tabs("exists", title)) {
                $mainTabs.tabs("select", title);
            } else {
                $mainTabs.tabs("add", {
                    title: title,
                    closable: true,
                    icon: icon,
                    content: createFrame(url)
                });
            }
        }

        function createFrame(url) {
            var html = '<iframe scrolling="auto" frameborder="0"  src="' + url + '" style="width:100%;height:100%;"></iframe>';
            return html;
        }

        function tabHandle(menu, type) {
            var title = $(menu).data("tabTitle");
            var $tab = $("#main-tab");
            var tabs = $tab.tabs("tabs");
            var index = $tab.tabs("getTabIndex", $tab.tabs("getTab", title));
            var closeTitles = [];
            switch (type) {
                case "tab-menu-refresh":
                    var iframe = $(".tabs-panels .panel").eq(index).find("iframe");
                    if (iframe) {
                        var url = iframe.attr("src");
                        iframe.attr("src", url);
                    }
                    break;
                case "tab-menu-openFrame":
                    var iframe = $(".tabs-panels .panel").eq(index).find("iframe");
                    if (iframe) {
                        window.open(iframe.attr("src"));
                    }
                    break;
                case "tab-menu-close":
                    closeTitles.push(title);
                    break;
                case "tab-menu-closeleft":
                    if (index == 0) {
                        $.OSky.layer.msg.tip("左边没有可关闭标签。");
                        return;
                    }
                    for (var i = 0; i < index; i++) {
                        var opt = $(tabs[i]).panel("options");
                        if (opt.closable) {
                            closeTitles.push(opt.title);
                        }
                    }
                    break;
                case "tab-menu-closeright":
                    if (index == tabs.length - 1) {
                        $.OSky.layer.msg.tip("右边没有可关闭标签。");
                        return;
                    }
                    for (var i = index + 1; i < tabs.length; i++) {
                        var opt = $(tabs[i]).panel("options");
                        if (opt.closable) {
                            closeTitles.push(opt.title);
                        }
                    }
                    break;
                case "tab-menu-closeother":
                    for (var i = 0; i < tabs.length; i++) {
                        if (i == index) {
                            continue;
                        }
                        var opt = $(tabs[i]).panel("options");
                        if (opt.closable) {
                            closeTitles.push(opt.title);
                        }
                    }
                    break;
                case "tab-menu-closeall":
                    for (var i = 0; i < tabs.length; i++) {
                        var opt = $(tabs[i]).panel("options");
                        if (opt.closable) {
                            closeTitles.push(opt.title);
                        }
                    }
                    break;
            }
            for (var i = 0; i < closeTitles.length; i++) {
                $tab.tabs("close", closeTitles[i]);
            }
        }

        function transToTreeData(data) {
            return $.Enumerable.From(data).Select(function(m) {
                var obj = {};
                obj.id = m.Id;
                obj.text = m.Text;
                obj.iconCls = m.IconCls;
                obj.checked = m.Checked;
                if (m.Url) {
                    obj.attributes = { url: m.Url };
                }
                if (m.Children && m.Children.length > 0) {
                    obj.children = transToTreeData(m.Children);
                }
                return obj;
            }).ToArray();
        }
    </script>
}

samples/OSky.UI.Admin/Areas/Admin/Views/Home/Welcome.cshtml
@using OSky.Web.Mvc.Extensions

@{
    ViewBag.Title = "Welcome";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Welcome</h2>
@*<ul>
    <li>组织机构数量：@ViewBag.Data.OrganizationCount</li>
    <li>角色数量：@ViewBag.Data.RoleCount</li>
    <li>用户数量：@ViewBag.Data.UserCount</li>
</ul>*@
<input id="btn1" type="button" class="btn btn-default" value="确 定">
<input id="btn2" type="button" class="btn btn-primary" value="确 定">
<input id="btn3" type="button" class="btn btn-success" value="确 定">
<input id="btn4" type="button" class="btn btn-info" value="确 定">
<input id="btn5" type="button" class="btn btn-warning " value="确 定">
<input id="btn6" type="button" class="btn btn-danger" value="确 定">
<br />
<input id="txt1" type="text" class="easyui-validatebox textbox" data-options="required:true,validType:'length[3,10]'" />
<select id="sel1" class="combo">
    <option value="1">请选择</option>
    <option value="2">你喜欢什么食物</option>
</select>
<select id="sel1" class="easyui-combobox">
    <option value="1">请选择</option>
    <option value="2">你喜欢什么食物</option>
</select>
<input class="easyui-textbox" data-options="multiline:true" style="height:60px" />


       @section footer{<script type="text/javascript">
            $(function () {
                $("#btn1").click(function () {
                    $.OSky.layer.msg.tab([{
                        title: 'TAB1',
                        content: '内容1'
                    }, {
                        title: 'TAB2',
                        content: '内容2'
                    }, {
                        title: 'TAB3',
                        content: '内容3'
                    }]);
                    //$.OSky.layer.msg.info("你好！");
                    //$.OSky.layer.msg.confirm("见到你真的很高兴", function() {alert("执行成功！") });
                    //$.OSky.layer.msg.full("welcome");
                    //$.OSky.layer.msg.open("你好！");
                    //var obj = $.OSky.layer.msg.prompt("你好！", '你还好吗？', function (obj) {
                    //    $.OSky.layer.msg.info(obj.pass + "-----" + obj.context);
                    //});

                });
                $("#btn2").click(function () {
                    $.OSky.layer.msg.loading(0);
                });
                $("#btn3").click(function () {
                    $.OSky.layer.msg.confirm("见到你真的很高兴", function () { alert("执行成功！") });
                });
                $("#btn4").click(function () {
                    $.OSky.layer.msg.open(1,"你好！",true, function (index, layero) {
                        $("#txt1").val("111");
                    },null,"查看");
                });
                $("#btn5").click(function () {
                    $.OSky.layer.msg.full(2, "welcome", true, function (index, layero) {
                        $("#txt2").val("111");
                    }, null, "查看");
                });
                $("#btn6").click(function () {
                    var obj = $.OSky.layer.msg.prompt("你好！", '你还好吗？', function (obj) {
                            $.OSky.layer.msg.info(obj.pass + "-----" + obj.context);
                        });
                });

            })

    </script>
}